name: Validate Commit Messages

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all commits
        run: git fetch --depth=0

      - name: Validate commit messages
        run: |
          # Fetch base and head SHA from pull_request event
          base_sha="${{ github.event.pull_request.base.sha }}"
          head_sha="${{ github.event.pull_request.head.sha }}"

          echo "Base SHA: $base_sha"
          echo "Head SHA: $head_sha"

          # Get commit messages between base and head
          commits=$(git log --no-merges --pretty=format:"%s" $base_sha..$head_sha)

          echo "Checking commit messages:"
          echo "$commits"

          # Define regex
          regex="^\[JIRA-[0-9]+\] (feat|fix|chore|docs|style|refactor|perf|test|build|ci)(\([^)]+\))?: .+"

          failed=0

          while IFS= read -r commit; do
            if [[ ! $commit =~ $regex ]]; then
              echo "::error ::Invalid commit message: '$commit'"
              failed=1
            fi
          done <<< "$commits"

          if [ "$failed" -eq 1 ]; then
            echo "One or more commit messages do not follow the conventional commit format."
            exit 1
          fi
