name: Check Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR commits with github-script
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.warning("⚠️ No pull_request context found (maybe running locally with act). Skipping description check.");
              return;
            }          
            const prNumber = pr.number;

            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const conventionalRegex = /^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([^\)]+\))?!?:\ .+/;

            let invalidCommits = [];

            for (const commit of commits.data) {
              const message = commit.commit.message.split('\n')[0]; // Only check the first line
              if (!conventionalRegex.test(message)) {
                invalidCommits.push(`❌ ${message}`);
              } else {
                console.log(`✅ ${message}`);
              }
            }

            if (invalidCommits.length > 0) {
              core.setFailed(`Found commits that do not follow Conventional Commits:\n${invalidCommits.join('\n')}`);
            }
