name: PR Title Format Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr?.title ?? "";
            console.log(`PR title: ${title}`);
