name: PR Description Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR description is empty
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            if (!prBody || prBody.trim().length === 0) {
              core.setFailed("❌ PR description is missing. Please provide a detailed description.");
            } else {
              console.log("✅ PR description found.");
            }
