name: PR Title Format Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr?.title ?? "";

            // Matches: [ABC-123] fix(core): Some message
            const pattern = /^\[[A-Z]+-\d+\]\s\S+(?:\([^)]+\))?:\s.+$/

            if (!pattern.test(title)) {
              core.setFailed(`❌ PR title "${title}" does not match the required format like "[TEST-123] fix(xyz): Your message"`);
            } else {
              console.log("✅ PR title format is valid.");
            }
