name: test suite
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/install-buck2
      - run: buck2 build //:hello_world --show-output